name: 機能追加・改善要望
description: 新しい機能や改善点の提案を書くテンプレート
title: "[Feature] "
labels: [enhancement]
body:
    - type: textarea
      id: summary
      attributes:
          label: 概要
          description: このIssueの目的や背景を簡潔に記述してください。
          placeholder: 例）ログイン後の遷移先でユーザー名を表示するようにしたい
      validations:
          required: true

    - type: textarea
      id: tasks
      attributes:
          label: やること
          description: 具体的な作業内容をリストアップしてください。
          placeholder: |
              - APIからユーザー名を取得
              - コンポーネントに表示処理を追加
              - テストコードの整備
      validations:
          required: false

    - type: textarea
      id: goal
      attributes:
          label: GOAL
          description: このIssueが完了したと判断する基準を書いてください。
          placeholder: 例）マイページでユーザー名が表示されていることを確認できる
      validations:
          required: false
