version: "3.8"

services:
    db:
        image: postgres:15
        container_name: postgres-local
        restart: always
        environment:
            POSTGRES_USER: local_user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: auth_db
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:
